version: '3.2'

services:

  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:80'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - VIRTUAL_HOST=dashboard.primalmkt.com
      - LETSENCRYPT_HOST=dashboard.primalmkt.com
      - LETSENCRYPT_EMAIL=soporte@primalmkt.com
networks:
  default:
    external:
      name: work
